In [ ]:
import numpy as np

In [ ]:
# eigen values and eigen vector
a = np.array([
     [1,2],
     [3,4]
])

eigenvalues, eigenvectors = np.linalg.eig(a)

print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

In [ ]:
# Singular value decomposition (SVD)
U, S, V = np.linalg.svd(a)

print("matrix u:")
print(U)
print("matrix s:")
print(S)
print("matrix v:")
print(V)

matrix u:
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
matrix s:
[5.4649857  0.36596619]
matrix v:
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

In [ ]:
import pandas as pd

#series
a = ['g', 'e', 'f', 's']

res = pd.Series(a)
print(res)

0    g
1    e
2    f
3    s
dtype: object

In [ ]:
a = {
    "id" : 12,
    "name" : "ahmed",
    "statte": "ktm",
}

res = pd.Series(a)
print(res)

id           12
name      ahmed
statte      ktm
dtype: object

In [ ]:
res.ndim

1

In [ ]:
# data frame
res_data = pd.DataFrame(res, columns = ["data1"])
print(res_data)

        data1
id         12
name    ahmed
statte    ktm

In [ ]:
res_data.ndim

2

In [ ]:
data = {
    "Name" : ["Defoe", "J.Terry", "Lampard"],
    "Team" : ["Newcastle", "Chelsea", "Chelsea"],
    "Number" : [23,5,22],
    "Age" : [33,38,None]
}

df = pd.DataFrame(data)
df

      Name       Team  Number   Age
0    Defoe  Newcastle      23  33.0
1  J.Terry    Chelsea       5  38.0
2  Lampard    Chelsea      22   NaN

In [ ]:
df["Name"]

0      Defoe
1    J.Terry
2    Lampard
Name: Name, dtype: object

In [ ]:
df[["Name","Age"]]

      Name   Age
0    Defoe  33.0
1  J.Terry  38.0
2  Lampard   NaN

In [ ]:
df[["Name","Team", "Number"]]

      Name       Team  Number
0    Defoe  Newcastle      23
1  J.Terry    Chelsea       5
2  Lampard    Chelsea      22

In [ ]:
df["Age"].isna()

0    False
1    False
2     True
Name: Age, dtype: bool

In [ ]:
print(df["Age"].isna().sum())

1

In [ ]:
#loc | Uses the explicit names of rows and columns. Slicing is inclusive of the end label.
res = df.loc[df["Name"]=="Defoe"]
res

    Name       Team  Number   Age
0  Defoe  Newcastle      23  33.0

In [ ]:
# iloc | Uses 0-based integer index numbers. Slicing is exclusive of the stop index (standard Python behavior).
df.iloc[0, 0]

'Defoe'

In [ ]:
df.iloc[0:2,0:2]

      Name       Team
0    Defoe  Newcastle
1  J.Terry    Chelsea

In [ ]:
#saving dataframe to csv
df.to_csv('data.csv',index=False)

In [ ]:
data = pd.read_csv('data.csv')
data

      Name       Team  Number   Age
0    Defoe  Newcastle      23  33.0
1  J.Terry    Chelsea       5  38.0
2  Lampard    Chelsea      22   NaN