In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
titanic_df = pd.read_csv("/content/drive/MyDrive/Data Science and Machine Learning/titanic-data.csv")

In [4]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
# renaming columns
titanic_df.rename(columns={"Name": "Passenger Name", "Sex": "Gender"}, inplace=True)
titanic_df.head()

,PassengerId,Survived,Pclass,Passenger Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Handling missing data

In [14]:
import numpy as np
data = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "name": ["Avik", "Ram", "Sita", "John", "Emma"],
    "age": [21, 25, 22, -30, "55"],
    "gender": ["M", "M", "Z", "M", "F"],
    "income": [35000, 42000, 38000, 55000, np.nan]
})
data

   id  name  age gender   income
0   1  Avik   21      M  35000.0
1   2   Ram   25      M  42000.0
2   3  Sita   22      Z  38000.0
3   4  John  -30      M  55000.0
4   5  Emma   55      F      NaN

In [15]:
# handling Incorrect data
data.dtypes

id          int64
name       object
age        object
gender     object
income    float64
dtype: object

In [16]:
data.age = data.age.astype(int)
data

   id  name  age gender   income
0   1  Avik   21      M  35000.0
1   2   Ram   25      M  42000.0
2   3  Sita   22      Z  38000.0
3   4  John  -30      M  55000.0
4   5  Emma   55      F      NaN

In [17]:
data.age = abs(data.age)
data

   id  name  age gender   income
0   1  Avik   21      M  35000.0
1   2   Ram   25      M  42000.0
2   3  Sita   22      Z  38000.0
3   4  John   30      M  55000.0
4   5  Emma   55      F      NaN

In [18]:
data.dtypes

id          int64
name       object
age         int64
gender     object
income    float64
dtype: object

In [20]:
#set boundries
filter_age = data[(data.age>=18)&(data.age<=45)]
filter_age

   id  name  age gender   income
0   1  Avik   21      M  35000.0
1   2   Ram   25      M  42000.0
2   3  Sita   22      Z  38000.0
3   4  John   30      M  55000.0

In [21]:
# isin |found keep it, not found discard it
data[data.gender.isin(["M","F"])]

   id  name  age gender   income
0   1  Avik   21      M  35000.0
1   2   Ram   25      M  42000.0
3   4  John   30      M  55000.0
4   5  Emma   55      F      NaN

In [22]:
# saving DataFrame
titanic_df.to_csv("Cleandata.csv", index=False)

In [23]:
data.to_json("cleandata.json", index=False, orient="records")

In [24]:
import pandas as pd

data = {
    "Gender": ["Male", "Male", "Male", "Female", "Female", "Female",
               "Male", "Female", "Male", "Female"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes", "No",
                  "Yes", "No", "Yes", "Yes"]
}

df = pd.DataFrame(data)

print(df)

   Gender Purchased
0    Male       Yes
1    Male        No
2    Male       Yes
3  Female        No
4  Female       Yes
5  Female        No
6    Male       Yes
7  Female        No
8    Male       Yes
9  Female       Yes

In [25]:
contigency_table = pd.crosstab(df["Gender"], df["Purchased"])
contigency_table

Purchased  No  Yes
Gender
Female      3    2
Male        1    4

In [27]:
# chi2_contigency
from scipy.stats import chi2_contingency

chi2, p_value, dof, expected = chi2_contingency(contigency_table)

print("Chi-squared statistics:", chi2)
print("Degree of freedom:", dof)
print("P-value:", p_value)
print(expected)

Chi-squared statistics: 0.41666666666666663
Degree of freedom: 1
P-value: 0.5186050164287255
[[2. 3.]
 [2. 3.]]

In [28]:
alpha = 0.05
if p_value < alpha:
  print("Reject the null hypothesis")
else:
  print("Fail to reject the null hypothesis")

Fail to reject the null hypothesis